import React from 'react'
import ReactDOM from 'react-dom/client'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { RouterProvider, createRouter } from '@tanstack/react-router'

// This file is auto-generated by the @tanstack/router-vite-plugin
import { routeTree } from './routeTree.gen'

const queryClient = new QueryClient()

// Create the router instance
const router = createRouter({
  routeTree,
  context: {
    queryClient,
    session: null, // These will be filled by the __root.tsx loader
    profile: null,
  },
  // Since you're using TanStack Query, you might want to 
  // let the query client handle the "loading" states
  defaultPreload: 'intent',
})

// Register the router for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </React.StrictMode>,
)